name: log_tanker
description: Logging package for flutter and dart focused on very fast set up. Entirely customizable and easy to use.
version: 0.0.2

repository: https://github.com/ObNitram/log_tanker
issue_tracker: https://github.com/ObNitram/log_tanker/issues



environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  ansicolor: ^2.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.3
